name: CI/CD

on:
  push:
    branches:
      - main
jobs: 
  build-and-deploy:
    runs-on: [ rhel-9 ]
    steps: 
      - name: Checkout source
        uses: actions/checkout@v4
      - name: setup node 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Generate Deployment Package 
        run: zip -r node-beanstalk-app-build.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'node-beanstalk-app'
          environment_name: 'node-beanstalk-app-env'
          version_label: ${{ github.sha }}
          region: ap-south-1
          deployment_package: node-beanstalk-app-build.zip
